# installed via nix flake
model_reasoning_effort = "high"
personality = "pragmatic"
# model_provider = "haystack"
# model = "claude-opus-4-6"

model_provider = "f5ai"
model = "gpt-5.4"
[model_providers.f5ai]
name = "f5ai"
base_url = "https://f5ai.pd.f5net.com/openai"  

[model_providers.haystack]
name = "haystack"
base_url = "http://haystack:4000/v1"  
env_key = "CODEX_PROXY_MASTER_KEY"
model_context_window = 200000
model_supports_reasoning_summaries = false

[projects."/Users/m.sawyer/workspaces/f5/volterra/ves.io/ares"]
trust_level = "trusted"

[projects."/Users/m.sawyer/workspaces/f5/volterra/ves.io/stdlib"]
trust_level = "trusted"

[projects."/Users/m.sawyer/workspaces/echolab"]
trust_level = "trusted"

[projects."/Users/m.sawyer/workspaces/f5/volterra/ves.io/specifications"]
trust_level = "trusted"

[notice.model_migrations]
"gpt-5.2-codex" = "gpt-5.3-codex"

[tui]
theme = "1337"

[features]
prevent_idle_sleep = true
