# installed via nix flake
model_reasoning_effort = "high"
personality = "pragmatic"
model_provider = "f5ai"
model = "gpt-5.4"
model_context_window = 1000000
model_auto_compact_token_limit = 800000

[model_providers.f5ai]
name = "f5ai"
base_url = "https://f5ai.pd.f5net.com/openai"  
model = "gpt-5.4"
model_context_window = 1000000
model_auto_compact_token_limit = 800000

[model_providers.haystack]
name = "haystack"
base_url = "http://haystack:4000/v1"  
env_key = "CODEX_PROXY_MASTER_KEY"
model_supports_reasoning_summaries = false

[projects."/Users/m.sawyer/workspaces/f5/volterra/ves.io/ares"]
trust_level = "trusted"

[projects."/Users/m.sawyer/workspaces/f5/volterra/ves.io/stdlib"]
trust_level = "trusted"

[projects."/Users/m.sawyer/workspaces/echolab"]
trust_level = "trusted"

[projects."/Users/m.sawyer/workspaces/f5/volterra/ves.io/specifications"]
trust_level = "trusted"

[notice.model_migrations]
"gpt-5.2-codex" = "gpt-5.3-codex"

[tui]
theme = "1337"

[features]
prevent_idle_sleep = true
rmcp_client = true

[mcp_servers.GitLab]
url = "https://gitlab.com/api/v4/mcp"

# [mcp_servers.Atlassian]
# command = "uvx"
# args = ["mcp-atlassian"]
# env_vars = [
#   "JIRA_URL",
#   "JIRA_PERSONAL_TOKEN",
#   "JIRA_SSL_VERIFY",
#   "CONFLUENCE_URL",
#   "CONFLUENCE_PERSONAL_TOKEN",
#   "CONFLUENCE_SSL_VERIFY",
# ]
