#!/usr/bin/env zsh

set -euo pipefail

profile=${AWS_PROFILE:-"f5xc-dev1-sre-console"}
region=${AWS_REGION:-us-east-2}
cluster_name=f5xc-dev1-gc01

current_identity=$(aws --profile $profile sts get-caller-identity 2>/dev/null || :)
if [[ -n "$current_identity" ]]; then
  printf "logged in as %s\n" $(echo "$current_identity" | jq -r '.Arn')
  kubectl cluster-info 2>/dev/null || aws --profile $profile eks update-kubeconfig --region $region --name $cluster_name
else
  echo "logging into aws with profile ${profile}..."
  aws --profile $profile configure sso
  echo "ensuring kube config for ${cluster_name}..."
  aws --profile $profile eks update-kubeconfig --region $region --name $cluster_name
fi
