#!/usr/bin/env zsh

# set -Eeo pipefail

declare -a tools=()
declare -a missing=()
declare -x message=''
while [[ -v 1 ]]; do
	message="$1"
	if [[ -z "$message" ]]; then
		break
	fi
	tools+=("$message")
	if ! command -v "$message" >/dev/null; then
		missing+=("$message")
	fi
	shift
done
if [[ -n "${missing[@]}" ]]; then
	echo "$message requires ${tools// /, }, but the following are missing: ${missing// /, }" >&2
	exit 1
fi
