#!/usr/bin/env zsh

set -Eeuo pipefail

if [[ -v 1 ]]; then
	repo="$1"
	branch=${2:-master}
	gcloud container images list-tags "gcr.io/volterraio/$repo" --format=json --sort-by=timestamp |
		jq -r '.[]|last(select(.tags|index("branch-'"$branch"'")))|.digest'
else
	echo "ERROR: must specify a repo" >&2
	exit 1
fi
