#!/usr/bin/env zsh

set -Eeuo pipefail

az acr login -n volterra --expose-token 2>/dev/null |
  jq -r '.accessToken' |
  skopeo login volterra.azurecr.io --username 00000000-0000-0000-0000-000000000000 --password-stdin 2>/dev/null
