#!/usr/bin/env zsh

set -Eeuo pipefail

root_dir=${ROOT_DIR:-${HOME}/workspaces}
url=$1
shift
labels=$(skopeo-inspect-labels $url)
if [[ "$?" -ne 0 ]]; then
	echo "could not inspect labels for $url" >&2
	exit 1
fi
if [[ -n "$labels" ]]; then
	repo_dir="$(printf '%s\n' $labels | jq -r '."com.f5.cloud.project-url"' | sd '^https://gitlab.com' $root_dir)"
	if [[ ! -d "$repo_dir" ]]; then
		repo_dir="${root_dir}/f5/volterra/ves.io/$(printf '%s\n' $labels | jq -r '.service')"
		if [[ ! -d "$repo_dir" ]]; then
			echo "could not determine repo dir for $url" >&2
			echo "found labels: ${labels}" >&2
			exit 1
		fi
	fi
	service="$(printf '%s\n' $labels | jq -r '."com.f5.cloud.app-name"')"
	commit="$(printf '%s\n' $labels | jq -r "to_entries|map(select(.key|contains(\"commit-sha\")))|first|.value")"
	if [[ -z "$commit" ]] || [[ "$commit" == "null" ]]; then
		echo "could not find commit label for $url" >&2
		exit 1
	fi
	git -C $repo_dir fetch origin --quiet && git -C $repo_dir log "$commit" $@
else
	echo "no labels found for $url" >&2
	exit 1
fi
