#!/usr/bin/env zsh

set -Eeuo pipefail

url="$1"
if [[ -z "$(echo "$url" | grep '^docker://')" ]]; then
	url="docker://$1"
fi
commit=$(skopeo inspect "$url" |
	jq -r '.Labels|to_entries|map(select(.key|contains("commit-sha")))|first|.value')
if [[ -z "$commit" ]] || [[ "$commit" == "null" ]]; then
	echo "could not find commit for $url" >&2
	exit 1
fi
echo $commit
