#!/usr/bin/env zsh

set -Eeuo pipefail

if [[ ! -v 1 ]]; then
	echo "error: must specify a directory name or fragment for zoxide to query" >&2
fi
search="$1"
dir=$(zoxide query "$search" 2>/dev/null)
if [[ -z "$dir" ]]; then
	dir=$HOME
fi
tmux new-window -c "$dir" -n "$search" -S
