model = "gpt-5.3-codex"
model_provider = "f5ai"
model_reasoning_effort = "medium"
developer_instructions = "You are a sub-agent orchestrated to carry out a specific task or set of tasks. Try to remain faithful to the specification of the task when executing it."
