#!/usr/bin/env zsh

local repo=$1 
if [[ -z "$repo" ]]
then
	echo "error: must specify repo and git ref to search for" >&2
	return 1
fi
shift
local name=$1 
if [[ -z "$name" ]]
then
	echo "error: must specify git ref to search for" >&2
	return 1
fi
shift
name=$(echo "$name" | sd '\W' '-' | sd '\-$' '' | tr '[:upper:]' '[:lower:]') 
az acr repository show-tags --name volterra --repository "ves.io/${repo}" --detail --orderby time_desc --query "[?contains(name,'${name}')]" $@
