#!/usr/bin/env zsh

check-required-tools $0 skopeo jq || return 1
if [[ $# -lt 1 ]]
then
	echo "usage: find-image-data [image-url|app-name commit-sha]" >&2
	return 1
fi
local app_name='' 
local commit_sha='' 
local image_data='' 
if [[ $# == 1 ]]
then
	image_url="$1" 
	image_data="$(skopeo inspect docker://${image_url} 2>/dev/null) | jq -r" 
	if [[ $? -ne 0 ]]
	then
		echo "error: unable to find image for ${image_url}" >&2
		return 1
	fi
else
	app_name="$1" 
	commit_sha="$2" 
	image_data="$(skopeo inspect docker://gcr.io/volterraio/${app_name}:${commit_sha} 2>/dev/null) | jq -r" 
	if [[ $? -ne 0 ]]
	then
		image_data="$(skopeo inspect docker://volterra.azurecr.io/ves.io/${app_name}:${commit_sha})" 
		if [[ $? -ne 0 ]]
		then
			acr-login
			image_data="$(skopeo inspect docker://volterra.azurecr.io/ves.io/${app_name}:${commit_sha} 2>/dev/null) | jq -r" 
			if [[ $? -ne 0 ]]
			then
				echo "error: unable to find image for ${app_name}:${commit_sha}" >&2
				echo "perhaps the pipeline failed or hasn't published an image yet, or perhaps the commit is gone from the origin?" >&2
				return 1
			fi
		fi
	fi
fi
echo "$image_data"
