#!/usr/bin/env zsh

export USE_GKE_GCLOUD_AUTH_PLUGIN=True 
kubectl config use-context gke_devtest-293809_us-east4_gc01-int-ves-io
k cluster-info 2> /dev/null || (
	gcloud auth login --project=devtest-293809 && gcloud container clusters get-credentials gc01-int-ves-io --region us-east4
)
