#!/usr/bin/env zsh

exit_code=$? 
current_cl=${history[$HISTCMD]} 
last_cmd=$(echo "$current_cl" | sed 's/;[^;]*$//' | sed 's/"//g') 
title="with title \"$last_cmd\"" 
if [[ -v 1 ]]
then
	title="with title \"$1\"" 
fi
if [[ $exit_code -eq 0 ]]
then
	osascript -e "display notification \"command succeeded\" $title sound name \"Funk\""
else
	osascript -e "display notification \"command failed\" $title sound name \"Sosumi\""
fi
return $exit_code
