#!/usr/bin/env zsh

set -Eeuo pipefail

url="$1"
if [[ -z "$(echo "$url" | grep '^docker://')" ]]; then
	url="docker://$1"
fi
labels=$(skopeo inspect "$url" |
	jq -r '.Labels')
if [[ -z "$labels" ]] || [[ "$labels" == "null" ]]; then
	echo "could not find labels for $url" >&2
	exit 1
fi
echo $labels
