#!/usr/bin/env zsh

if [[ $# -lt 1 ]]; then
	echo >&2 "must specify the image url"
	exit 1
fi
url="$1"

set -Eeuo pipefail

if ! (echo "$url" | grep '^docker://' >/dev/null); then
	url="docker://$1"
fi
skopeo inspect "$url" | jq -r '.Digest'
