#!/usr/bin/env zsh

if [[ ! -v 1 ]]
then
	echo "error: must specify a directory name or fragment for zoxide to query" >&2
fi
local search="$1" 
local dir=$(zoxide query "$search" 2>/dev/null) 
if [[ -z "$dir" ]]
then
	dir=$HOME 
fi
local tab_id=$(wezterm cli list --format json | jq -r "map(select(.tab_title==\"${search}\"))|map(.tab_id)[]") 
if [[ -z "$tab_id" ]]
then
	wezterm cli spawn --cwd "$dir" sh -c "wezterm cli set-tab-title $search; zsh -i"
	sleep 1
	tab_id=$(wezterm cli list --format json | jq -r "map(select(.tab_title==\"${search}\"))|map(.tab_id)[]") 
fi
wezterm cli activate-tab --tab-id "$tab_id"
